# Generated by Django 5.2.8 on 2025-11-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=50)),
                ('quantite', models.PositiveIntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('Neuf', 'Neuf'), ('Bon', 'Bon'), ('Endommagé', 'Endommagé')], max_length=50)),
            ],
        ),
    ]
